language: go
sudo: required

services:
    - docker

go:
    - 1.12.x

install:
    - go get golang.org/x/lint/golint

script:
    - make binary
    - go vet $(go list ./... | grep -v vendor)
    - test -z "$(golint ./... | grep -v vendor | tee /dev/stderr)"
    - test -z "$(gofmt -s -l . | grep -v vendor | tee /dev/stderr)"

    # Make cross
    - make cross
    # ignore extra variants for arm; use v7 as default:
    - cp manifest-tool-linux-armv7 manifest-tool-linux-arm
    # Build all images
    - docker build --build-arg PLATFORM=linux-amd64 -t mplatform/manifest-tool:linux-amd64 -f hack/Dockerfile.linux .
    - docker build --build-arg PLATFORM=linux-arm -t mplatform/manifest-tool:linux-arm -f hack/Dockerfile.linux .
    - docker build --build-arg PLATFORM=linux-arm64 -t mplatform/manifest-tool:linux-arm64 -f hack/Dockerfile.linux .
    - docker build --build-arg PLATFORM=linux-ppc64le -t mplatform/manifest-tool:linux-ppc64le -f hack/Dockerfile.linux .
    - docker build --build-arg PLATFORM=linux-s390x -t mplatform/manifest-tool:linux-s390x -f hack/Dockerfile.linux .

    # Test at least Intel image
    - docker run mplatform/manifest-tool:linux-amd64 inspect busybox:latest

    - >
      if [ -n "$TRAVIS_TAG" ]; then
        # Push all images
        travis_retry timeout 5m docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"

        docker tag mplatform/manifest-tool:linux-amd64 mplatform/manifest-tool:${TRAVIS_TAG}-linux-amd64
        docker tag mplatform/manifest-tool:linux-arm mplatform/manifest-tool:${TRAVIS_TAG}-linux-arm
        docker tag mplatform/manifest-tool:linux-arm64 mplatform/manifest-tool:${TRAVIS_TAG}-linux-arm64
        docker tag mplatform/manifest-tool:linux-ppc64le mplatform/manifest-tool:${TRAVIS_TAG}-linux-ppc64le
        docker tag mplatform/manifest-tool:linux-s390x mplatform/manifest-tool:${TRAVIS_TAG}-linux-s390x
        # push version for each platform
        docker push mplatform/manifest-tool:${TRAVIS_TAG}-linux-amd64
        docker push mplatform/manifest-tool:${TRAVIS_TAG}-linux-arm
        docker push mplatform/manifest-tool:${TRAVIS_TAG}-linux-arm64
        docker push mplatform/manifest-tool:${TRAVIS_TAG}-linux-ppc64le
        docker push mplatform/manifest-tool:${TRAVIS_TAG}-linux-s390x

        # Push manifest-list
        ./manifest-tool push from-args --platforms linux/amd64,linux/arm,linux/arm64,linux/ppc64le,linux/s390x,windows/amd64 --template "mplatform/manifest-tool:${TRAVIS_TAG}-OS-ARCH" --target "mplatform/manifest-tool:$TRAVIS_TAG"
        ./manifest-tool push from-args --platforms linux/amd64,linux/arm,linux/arm64,linux/ppc64le,linux/s390x,windows/amd64 --template "mplatform/manifest-tool:${TRAVIS_TAG}-OS-ARCH" --target "mplatform/manifest-tool:latest"
      fi
