version: 1.0.{build}
image: Visual Studio 2017

clone_folder: c:\gopath\src\github.com\estesp\manifest-tool

environment:
  GOPATH: C:\gopath
  CGO_ENABLED: 1
  matrix:
    - GO_VERSION: 1.11

before_build:
  - choco install -y mingw --version 5.3.0
  # Install Go
  - rd C:\Go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GO_VERSION%.windows-amd64.zip
  - 7z x go%GO_VERSION%.windows-amd64.zip -oC:\ >nul
  - go version

build_script:
  - bash.exe -elc "export PATH=/c/tools/mingw64/bin:$PATH ; mingw32-make.exe binary"
  - docker build -t mplatform/manifest-tool:windows-amd64 -f hack/Dockerfile.windows .

test_script:
  - docker run mplatform/manifest-tool:windows-amd64 inspect alpine:latest 

deploy_script:
  - ps: >-
      if (Test-Path Env:\APPVEYOR_REPO_TAG_NAME) {

        docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
        docker tag mplatform/manifest-tool:windows-amd64 mplatform/manifest-tool:$($env:APPVEYOR_REPO_TAG_NAME)-windows-amd64
        docker push mplatform/manifest-tool:$($env:APPVEYOR_REPO_TAG_NAME)-windows-amd64

      }
